# Logging settings
logging:
  level:
    root: ERROR
    com:
      kon: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: ./log/output.log
  logback:
    rollingpolicy:
      max-file-size: ${LOGGING_FILE_MAX_SIZE:100MB}
      max-history: ${LOGGING_FILE_MAX_HISTORY:50}


