// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.kon.hello;

public interface StreamReqDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.StreamReqData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
